### ISSUE TITLE
Как сделать фильтр по свойствам товара?

### ISSUE THREAD

**Issue by pimshtein** [GdeSlon/wp-affiliate-shop#24]
Все свойства - индивидуальные. Но фильтры существуют только для тех, которые были добавлены в "Свойства".
Как быть?

**Comment by aiiddqd** [comment]
Найти программистов, которые смогут написать расширение для этой задачи.

К примеру есть модуль ACF который позволет добавлять свойства в зависимости от категории товара. Но в фильтр они не пойдут сами. Надо дописывать фильтр.

Наша компания оказывает такие услуги http://systemo.biz/razrabotka-wordpress/
Можете там подать заявку и получить оценку работ от специалистов.

**Comment by letions** [comment]
Здравствуйте! Помогу загрузить товары с прайс-листа на OpenCart или Ostore — смотрятся сайты намного солиднее на данных CMS. Вот пример — http://myopencart.com/ .
В карточке товара будут помимо основного фото — дополнительные фото, актуальная цена, заголовок, наличие товара, описание, характеристики с атрибутами — все как на сайте рекламодателя!
Создам интернет-магазин с Вашим прайсом.
Пишите на letions@mail.ru
